services:
  - type: web
    name: irlobby-backend
    runtime: python
    rootDir: irlobby_backend
    buildCommand: "pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput"
    startCommand: "gunicorn irlobby_backend.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: irlobby-backend.onrender.com
      - key: DATABASE_URL
        value: postgresql://irlobby_database_user:31RjDu8kjXIlo3Tya44e7faECt5h9qCG@dpg-d2v6oaer433s73etgfkg-a/irlobby_database
      - key: CORS_ALLOWED_ORIGINS
        value: https://irlobby-ovkujb5lr-aaron-esbenshades-projects.vercel.app,http://localhost:3000,http://127.0.0.1:3000,exp://localhost:8081

  - type: worker
    name: irlobby-channels
    runtime: python
    rootDir: irlobby_backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "daphne -b 0.0.0.0 -p 8001 irlobby_backend.asgi:application"
    envVars:
      - key: DEBUG
        value: false
      - key: DJANGO_SETTINGS_MODULE
        value: irlobby_backend.settings
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: irlobby-channels.onrender.com
      - key: DATABASE_URL
        value: postgresql://irlobby_database_user:31RjDu8kjXIlo3Tya44e7faECt5h9qCG@dpg-d2v6oaer433s73etgfkg-a/irlobby_database
