services:
  - type: web
    name: irlobby-backend
    runtime: python
    rootDir: irlobby_backend
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "python manage.py migrate && gunicorn irlobby_backend.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: irlobby-backend.onrender.com,irlobby-channels.onrender.com,localhost,127.0.0.1
      - key: DATABASE_URL
        value: postgresql://irlobby_database_user:31RjDu8kjXIlo3Tya44e7faECt5h9qCG@dpg-d2v6oaer433s73etgfkg-a/irlobby_database
      - key: CORS_ALLOWED_ORIGINS
        value: https://irlobby.vercel.app,http://localhost:5173,http://127.0.0.1:5173,http://localhost:3000,http://127.0.0.1:3000,exp://localhost:8081
      - key: TWITTER_CLIENT_ID
        value: RXZvYVQ5ZVhySnRJUmlmRnNuYzM6MTpjaQ
      - key: TWITTER_CLIENT_SECRET
        value: WwXb8YvVx52DIpsSOyA8MAX9vfhR46uClyKok3zFMhMxYZgpsR

  - type: worker
    name: irlobby-channels
    runtime: python
    rootDir: irlobby_backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "DJANGO_SETTINGS_MODULE=irlobby_backend.settings daphne -b 0.0.0.0 -p 8001 irlobby_backend.asgi:application"
    envVars:
      - key: DEBUG
        value: false
      - key: DJANGO_SETTINGS_MODULE
        value: irlobby_backend.settings
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: irlobby-backend.onrender.com,irlobby-channels.onrender.com,localhost,127.0.0.1
      - key: DATABASE_URL
        value: postgresql://irlobby_database_user:31RjDu8kjXIlo3Tya44e7faECt5h9qCG@dpg-d2v6oaer433s73etgfkg-a/irlobby_database
      - key: CORS_ALLOWED_ORIGINS
        value: https://irlobby.vercel.app,http://localhost:5173,http://127.0.0.1:5173,http://localhost:3000,http://127.0.0.1:3000,exp://localhost:8081
      - key: TWITTER_CLIENT_ID
        value: RXZvYVQ5ZVhySnRJUmlmRnNuYzM6MTpjaQ
      - key: TWITTER_CLIENT_SECRET
        value: WwXb8YvVx52DIpsSOyA8MAX9vfhR46uClyKok3zFMhMxYZgpsR
