services:
  - type: web
    name: irlobby-backend
    runtime: python
    rootDir: irlobby_backend
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "python manage.py migrate && gunicorn irlobby_backend.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: irlobby-backend.onrender.com,irlobby-channels.onrender.com,localhost,127.0.0.1
      - key: DATABASE_URL
        value: postgresql://irlobby_database_user:31RjDu8kjXIlo3Tya44e7faECt5h9qCG@dpg-d2v6oaer433s73etgfkg-a/irlobby_database
      - key: CORS_ALLOWED_ORIGINS
        value: https://irlobby-l4sovrh3c-aaron-esbenshades-projects.vercel.app,http://localhost:3000,http://127.0.0.1:3000,exp://localhost:8081
      - key: TWITTER_CLIENT_ID
        value: RXZvYVQ5ZVhySnRJUmlmRnNuYzM6MTpjaQ
      - key: TWITTER_CLIENT_SECRET
        value: 5L8a9KpmZ6fCBOlzBJw0kDWXYLo5qT4s_gQ4PDf5F2ucPohIXM
      - key: EMAIL_BACKEND
        value: django.core.mail.backends.smtp.EmailBackend
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USE_TLS
        value: true
      - key: EMAIL_HOST_USER
        value: ajesbenshade@gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: nrrz gagq bdrk fxbx
      - key: DEFAULT_FROM_EMAIL
        value: noreply@irlobby.com
      - key: FRONTEND_URL
        value: https://irlobby-l4sovrh3c-aaron-esbenshades-projects.vercel.app

  - type: worker
    name: irlobby-channels
    runtime: python
    rootDir: irlobby_backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "DJANGO_SETTINGS_MODULE=irlobby_backend.settings daphne -b 0.0.0.0 -p 8001 irlobby_backend.asgi:application"
    envVars:
      - key: DEBUG
        value: false
      - key: DJANGO_SETTINGS_MODULE
        value: irlobby_backend.settings
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: irlobby-backend.onrender.com,irlobby-channels.onrender.com,localhost,127.0.0.1
      - key: DATABASE_URL
        value: postgresql://irlobby_database_user:31RjDu8kjXIlo3Tya44e7faECt5h9qCG@dpg-d2v6oaer433s73etgfkg-a/irlobby_database
      - key: CORS_ALLOWED_ORIGINS
        value: https://irlobby-l4sovrh3c-aaron-esbenshades-projects.vercel.app,http://localhost:3000,http://127.0.0.1:3000,exp://localhost:8081
      - key: TWITTER_CLIENT_ID
        value: RXZvYVQ5ZVhySnRJUmlmRnNuYzM6MTpjaQ
      - key: TWITTER_CLIENT_SECRET
        value: ****UXyweT
      - key: EMAIL_BACKEND
        value: django.core.mail.backends.smtp.EmailBackend
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USE_TLS
        value: true
      - key: EMAIL_HOST_USER
        value: ajesbenshade@gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: nrrz gagq bdrk fxbx
      - key: DEFAULT_FROM_EMAIL
        value: noreply@irlobby.com
      - key: FRONTEND_URL
        value: https://irlobby-l4sovrh3c-aaron-esbenshades-projects.vercel.app
